"""add body_html

Revision ID: 58121be3537c
Revises: 
Create Date: 2018-04-24 23:38:07.071444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58121be3537c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    # ### end Alembic commands ###
